import { orange, neutral, yellow, green, red } from "./colors";
import { primaryFont } from "./typography";

export const defaultTheme = {
  primaryColor: orange[300],
  primaryHoverColor: orange[200],
  primaryActiveColor: orange[400],
  textColorOnPrimary: neutral[100],
  textColor: neutral[600],
  textColorInverted: neutral[100],
  formElementBackground: neutral[100],
  textOnFormElementBackground: neutral[600],
  primaryFont,
  disabled: neutral[400],
  textOnDisabled: neutral[300],
  textFieldBackground: neutral[200],
  textFieldLabelColor: neutral[500],
  tertiaryBorderColor: neutral[100],
  background: neutral[100],
  status: {
    warningColor: yellow[200],
    warningColorHover: yellow[100],
    warningColorActive: yellow[300],
    errorColor: red[200],
    errorColorHover: red[100],
    errorColorActive: red[300],
    successColor: green[200],
    successColorHover: green[100],
    successColorActive: green[300],
  },
};

export const darkTheme = {
  primaryColor: neutral[100],
  primaryHoverColor: neutral[200],
  primaryActiveColor: neutral[300],
  textColorOnPrimary: orange[300],
  textColor: orange[300],
  textColorInverted: neutral[100],
  formElementBackground: orange[100],
  textOnFormElementBackground: neutral[100],
  primaryFont,
  disabled: neutral[400],
  textOnDisabled: neutral[300],
  textFieldBackground: neutral[200],
  textFieldLabelColor: neutral[100],
  tertiaryBorderColor: neutral[600],
  background: neutral[600],
  status: {
    warningColor: yellow[100],
    warningColorHover: yellow[200],
    warningColorActive: yellow[300],
    errorColor: red[100],
    errorColorHover: red[200],
    errorColorActive: red[300],
    successColor: green[100],
    successColorHover: green[200],
    successColorActive: green[300],
  },
};
